export interface Product {
  key: string;
  label: string;
  emoji: string;
  category: string;
  aliases?: string[];
}

export const PRODUCT_CATEGORIES = [
  { id: "veg", label: "Sabzavotlar", emoji: "🥕" },
  { id: "greens", label: "Ko'kat & Ziravor", emoji: "🌿" },
  { id: "meat", label: "Go'sht & Baliq", emoji: "🥩" },
  { id: "dairy", label: "Sut & Tuxum", emoji: "🥛" },
  { id: "grain", label: "Un & Don", emoji: "🌾" },
  { id: "fruit", label: "Mevalar", emoji: "🍎" },
  { id: "nuts", label: "Yong'oq & Urug'", emoji: "🥜" },
  { id: "pantry", label: "Yog' & Souslar", emoji: "🫒" },
] as const;

const P = (
  key: string,
  label: string,
  emoji: string,
  category: string,
  aliases: string[] = [],
): Product => ({ key, label, emoji, category, aliases });

export const PRODUCTS: Product[] = [
  // 🥕 Sabzavotlar
  P("sabzi", "Sabzi", "🥕", "veg", ["sariq sabzi", "qizil sabzi"]),
  P("piyoz", "Piyoz", "🧅", "veg", ["qizil piyoz", "ko'k piyoz", "sharlot piyoz"]),
  P("kartoshka", "Kartoshka", "🥔", "veg"),
  P("batat", "Shirin kartoshka", "🍠", "veg", ["batat"]),
  P("sarimsoq", "Sarimsoq", "🧄", "veg"),
  P("pomidor", "Pomidor", "🍅", "veg", ["tomat"]),
  P("bodring", "Bodring", "🥒", "veg"),
  P("bulgor", "Bulg'or qalampiri", "🫑", "veg", ["bolg'or"]),
  P("achchiq", "Achchiq qalampir", "🌶️", "veg", ["chili", "jalapeno"]),
  P("karam", "Karam", "🥬", "veg"),
  P("zucchini", "Qovoqcha", "🥒", "veg", ["zucchini"]),
  P("lavlagi", "Lavlagi", "🥬", "veg"),
  P("qoziqorin", "Qo'ziqorin", "🍄", "veg", ["shampinyon", "veshenka"]),
  // 🌿 Ko'kat & Ziravor
  P("ispanoq", "Ispanoq / Kale", "🥬", "greens", ["kale", "mangold", "xardal barglari"]),
  P("kashnich", "Kashnich", "🌿", "greens"),
  P("petrushka", "Petrushka", "🌿", "greens"),
  P("ukrop", "Ukrop", "🌿", "greens"),
  P("rayhon", "Rayhon", "🌿", "greens", ["basil", "reyhan"]),
  P("yalpiz", "Yalpiz", "🌿", "greens"),
  P("shivit", "Shivit", "🌿", "greens"),
  P("rozmarin", "Rozmarin", "🌿", "greens"),
  P("timyan", "Timyan", "🌿", "greens"),
  P("estragon", "Estragon", "🌿", "greens"),
  P("zira", "Zira", "🟤", "greens"),
  P("koriandr", "Koriandr", "🌱", "greens"),
  P("kurkuma", "Kurkuma", "🟡", "greens"),
  P("karri", "Karri", "🍛", "greens"),
  P("dolchin", "Dolchin", "🍂", "greens", ["dolchin kukuni"]),
  P("hil", "Hil (kardamon)", "🌱", "greens", ["kardamon"]),
  P("zanjabil", "Zanjabil", "🫚", "greens"),
  P("vanil", "Vanil", "🌼", "greens", ["vanil ekstrakti", "vanillin"]),
  P("tuz", "Tuz", "🧂", "greens"),
  P("murch", "Qora murch", "⚫", "greens", ["murch"]),
  // 🥩 Go'sht & Baliq
  P("mol", "Mol go'shti", "🥩", "meat", ["mol go'shti", "mol tili", "mol jigari"]),
  P("qoy", "Qo'y go'shti", "🍖", "meat", ["qo'y go'shti", "qovurg'a"]),
  P("tovuq", "Tovuq", "🍗", "meat"),
  P("qiyma", "Qiyma", "🍖", "meat"),
  P("jigar", "Jigar", "🍖", "meat"),
  P("bekon", "Bekon", "🥓", "meat"),
  P("somon", "Somon (losos)", "🐟", "meat", ["losos", "baliq"]),
  P("qazi", "Qazi", "🍖", "meat"),
  // 🥛 Sut & Tuxum
  P("tuxum", "Tuxum", "🥚", "dairy"),
  P("sut", "Sut", "🥛", "dairy"),
  P("qaymoq", "Qaymoq", "🍶", "dairy", ["heavy cream"]),
  P("saryog", "Sariyog'", "🧈", "dairy", ["saryog'"]),
  P("qatiq", "Qatiq / Kefir", "🥛", "dairy", ["kefir", "buttermilk"]),
  P("smetana", "Smetana", "🥛", "dairy"),
  P("yogurt", "Yogurt", "🥛", "dairy"),
  P("suzma", "Suzma / Qatiq", "🥛", "dairy"),
  P("tvorog", "Tvorog / Cream cheese", "🧀", "dairy", ["cream cheese"]),
  P("pishloq", "Pishloq", "🧀", "dairy", ["motsarella", "cheddar", "xallumi", "parmezan", "feta", "brynza", "echki pishlog'i", "rikotta"]),
  P("muzqaymoq", "Muzqaymoq", "🍨", "dairy"),
  P("kondensat", "Quyultirilgan sut", "🥫", "dairy", ["quyultirilgan sut", "sgushchenka", "kondensirovannoye"]),
  // 🌾 Un & Don
  P("guruch", "Guruch", "🍚", "grain", ["devzira", "lazer"]),
  P("un", "Un", "🌾", "grain", ["bug'doy uni"]),
  P("javdar", "Javdar uni", "🌾", "grain"),
  P("suli", "Suli uni / yormasi", "🥣", "grain", ["suli"]),
  P("makkoun", "Makkajo'xori uni", "🌽", "grain", ["cornmeal"]),
  P("kraxmal", "Kraxmal", "🥣", "grain"),
  P("manna", "Manna yarmasi", "🥣", "grain", ["manka"]),
  P("makaron", "Makaron / Spagetti", "🍝", "grain", ["spagetti", "pasta"]),
  P("xamirturush", "Xamirturush", "🫧", "grain", ["drojji", "sourdough", "hamirturush"]),
  P("kreker", "Kreker", "🍪", "grain", ["grek krekeri"]),
  P("non", "Non / Muffin", "🍞", "grain", ["muffin"]),
  P("nohot", "Nohut", "🫘", "grain", ["noxat", "nohot"]),
  P("lobiya", "Lobiya", "🫘", "grain", ["loviya", "qora lobiya"]),
  P("kinoa", "Kinoa / Yarma", "🥣", "grain", ["kinoa", "yarma", "farro", "bulg'or"]),
  // 🍎 Mevalar
  P("olma", "Olma", "🍎", "fruit"),
  P("limon", "Limon", "🍋", "fruit"),
  P("laym", "Laym", "🍋", "fruit"),
  P("apelsin", "Apelsin", "🍊", "fruit"),
  P("greypfrut", "Greypfrut", "🍊", "fruit"),
  P("banan", "Banan", "🍌", "fruit"),
  P("qulupnay", "Qulupnay", "🍓", "fruit"),
  P("chernika", "Chernika", "🫐", "fruit", ["smorodina"]),
  P("mango", "Mango", "🥭", "fruit"),
  P("ananas", "Ananas", "🍍", "fruit"),
  P("tarvuz", "Tarvuz", "🍉", "fruit"),
  P("qovun", "Qovun", "🍈", "fruit"),
  P("shaftoli", "Shaftoli", "🍑", "fruit"),
  P("orik", "O'rik", "🍑", "fruit"),
  P("olxori", "Olxori", "🍇", "fruit"),
  P("mayiz", "Mayiz", "🍇", "fruit"),
  P("xurmo", "Xurmo (unab)", "🌰", "fruit", ["unab", "xurmo"]),
  P("anor", "Anor", "🔴", "fruit"),
  P("nok", "Nok", "🍐", "fruit"),
  P("avokado", "Avokado", "🥑", "fruit"),
  // 🥜 Yong'oq & Urug'
  P("yongoq", "Yong'oq", "🌰", "nuts", ["gretskiy", "pekan"]),
  P("bodom", "Bodom", "🌰", "nuts"),
  P("funduk", "Funduk", "🌰", "nuts"),
  P("pista", "Pista", "🥜", "nuts"),
  P("yeryongoq", "Yer-yong'oq", "🥜", "nuts", ["peanut"]),
  P("kunchut", "Kunchut", "⚪", "nuts", ["sezam", "taxini"]),
  P("qovoqurug", "Qovoq urug'i", "🎃", "nuts", ["pepitas"]),
  P("kokos", "Kokos", "🥥", "nuts", ["kokos qiyg'ichi"]),
  // 🫒 Yog' & Souslar
  P("osyog", "O'simlik yog'i", "🫒", "pantry", ["o'simlik yog'i", "paxta yog'i"]),
  P("zaytun", "Zaytun yog'i", "🫒", "pantry"),
  P("kokosyog", "Kokos yog'i / suti", "🥥", "pantry", ["kokos suti", "kokos yog'i"]),
  P("soya", "Soya sousi", "🍶", "pantry", ["soya sousi", "soyali"]),
  P("sirka", "Sirka", "🍶", "pantry", ["olma sirkasi", "guruch sirkasi", "sirka"]),
  P("tomat", "Tomat pastasi", "🥫", "pantry", ["tomat pastasi", "pomidor pastasi", "djem"]),
  P("asal", "Asal", "🍯", "pantry"),
  P("shakar", "Shakar", "🍬", "pantry"),
  P("jshakar", "Jigarrang shakar", "🍬", "pantry", ["jigarrang shakar"]),
  P("pudra", "Shakar kukuni", "🍬", "pantry", ["shakar kukuni", "pudra"]),
  P("kakao", "Kakao", "🍫", "pantry"),
  P("shokolad", "Shokolad", "🍫", "pantry"),
  P("qahva", "Qahva", "☕", "pantry", ["espresso"]),
  P("matcha", "Matcha choy", "🍵", "pantry", ["choy"]),
  P("mayonez", "Mayonez", "🥫", "pantry"),
  P("xardal", "Xardal", "🟡", "pantry", ["dijon"]),
  P("kimchi", "Kimchi", "🥬", "pantry"),
];

export function getProduct(key: string): Product | undefined {
  return PRODUCTS.find((p) => p.key === key);
}
